### ISSUE TITLE
Can't build mconnect on Fedora 24

### ISSUE THREAD

**Issue by Paviluf** [bboozzoo/mconnect#6] opened 2016-06-29 20:01 UTC
Hello,

I want to try mconnect on Fedora 24 but I can't build it. This is what I have made :
```
$ sudo dnf install vala glib2-devel gobject-introspection-devel libgee-devel openssl-devel libnotify-devel json-glib-devel
$ git clone https://github.com/bboozzoo/mconnect.git
$ cd mconnect
$ autoreconf -if
$ ./configure --prefix=/usr
$ make
```
*Note that json-glib on the readme explanation have to be replaced by json-glib-devel.*

At the "make" step there is this error :
```
sed -e 's,[@]bindir[@],/usr/bin,g' < mconnect.desktop.in > mconnect.desktop
  VALAC    mconnect_vala.stamp
gee-0.8.vapi:267.4-267.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-0.8.vapi:662.4-662.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-0.8.vapi:664.4-664.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-0.8.vapi:672.4-672.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-0.8.vapi:674.4-674.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
src/mconnect/devicechannel.vala:111.16-112.29: error: Assignment: Cannot convert from `GLib.Source' to `GLib.SocketSource?'
src/mconnect/devicechannel.vala:113.3-113.8: error: The name `source' does not exist in the context of `DeviceChannel.open'
		source.set_callback((src, cond) => {
		^^^^^^
src/mconnect/devicechannel.vala:118.12-118.17: error: The name `source' does not exist in the context of `DeviceChannel.open'
		_srcid = source.attach(null);
		         ^^^^^^
src/mconnect/device.vala:79.20-79.53: warning: unhandled error `GLib.KeyFileError'
		this.device_id = cache.get_string(name, "deviceId");
		                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/mconnect/device.vala:80.22-80.57: warning: unhandled error `GLib.KeyFileError'
		this.device_name = cache.get_string(name, "deviceName");
		                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/mconnect/device.vala:81.22-81.57: warning: unhandled error `GLib.KeyFileError'
		this.device_type = cache.get_string(name, "deviceType");
		                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/mconnect/device.vala:82.27-82.68: warning: unhandled error `GLib.KeyFileError'
		this.protocol_version = cache.get_integer(name, "protocolVersion");
		                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/mconnect/device.vala:83.26-83.59: warning: unhandled error `GLib.KeyFileError'
		this.tcp_port = (uint) cache.get_integer(name, "tcpPort");
		                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/mconnect/device.vala:84.21-84.59: warning: unhandled error `GLib.KeyFileError'
		var last_ip_str = cache.get_string(name, "lastIPAddress");
		                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/mconnect/discovery.vala:55.24-58.5: error: lambda expression: too many parameters
Compilation failed: 4 error(s), 11 warning(s)
Makefile:1047 : la recette pour la cible « mconnect_vala.stamp » a échouée
make: *** [mconnect_vala.stamp] Erreur 1
```
How can this be fixed ? I also noticed that you have a copr repo but it's not maintained anymore. Can you update it please ?

Thanks !

Ps. Is mconnect still an active project ?

**Comment by bboozzoo** [comment] 2016-06-30 06:14
Indeed, it fails to build on F24. Didn't really notice that as F23 package still worked after `dnf system-upgrade`. I'll check what the problem is.

As for being an active project, it's kind of alive. I still use it every day ;) Had some work queued up, but didn't really have time to wrap my head around it. 
It'd be nice to have a dbus interface and some rudimentary cli at least (I've started moving to GLib.Application in bboozzoo/dbus-support branch). 
Then there's a problem with the same notification appearing a couple of time, a simple `id` check as it's done now is not sufficient. I guess it's better to have a hash of the message & timestamp and check this instead.

**Comment by Paviluf** [comment] 2016-06-30 09:27
Glad to hear that it's still alive :) I hope you will find time to improve it further, it's a good soft for people that are not on KDE and don't want to install a lot of kde dependencies.

About the copr repo any chance that you will update it ?

**Comment by bboozzoo** [comment] 2016-06-30 09:28
I'll update the repo once I can build the code on F24, doesn't make sene to do it any sooner.

**Comment by Paviluf** [comment] 2016-06-30 09:30
Of course. Thanks !

**Comment by bboozzoo** [comment] 2016-07-02 07:27
Ok, so the problem is a bit complicated than expected. Vala bindings to gio-2.0 have changed and a bug was introduced where calling `Socket.create_source()` generates a C call to `g_socket_datagram_based_create_source()`, while it should call `g_socket_create_source()` instead. I've tracked down the commit that introduced the bug and I'll try to work with upstream to get it fixed. Meanwhile, I'll implement a workaround just to have something working.

**Comment by Paviluf** [comment] 2016-07-02 08:14
That's an amazing work ! Thank you so much.

**Comment by bboozzoo** [comment] 2016-07-02 21:52
@Paviluf can you check if `bboozzoo/socket-source` branch builds and works fine on your system?

**Comment by Paviluf** [comment] 2016-07-03 00:24
That seems to build without problem. Thanks ! 

I'm sorry to say that but now that I can test it, almost nothing work :D I'm a bit disapointed but I will report the issues I have with more details tomorrow. I can already say that I'm connected but it's not straightforward (need a few try to work and can only accept connection from the phone), I had to manually open the ports 1714-1764 tcp/udp and I can't send or receive files.

Thanks again !

**Comment by Paviluf** [comment] 2016-07-03 11:33
I just want to use mconnect to send and receive file so I just tested this feature and here is my experience so far.

**Connection**
In order to make it work this is what I have to do :
- Launch kde connect on the phone
- Launch mconnect on the PC
- Ask to pair on phone (don't work)
- Cancel the pairing on the phone (go back)
- Close mconnect
- Launch mconnect
- If a demand of connection appear on the phone accept it
- Else retry

If I launch mconnect before kde connect on the phone they don't see them.

**Send files from the phone to PC**
- I can send files but that fail

**Send files from the PC to the phone**
- Nothing appear in Nautilus so I can't send file to the phone

If you need more infos or logs just say it. I hope that all of this is fixable ;)
Thanks !

**Comment by Paviluf** [comment] 2016-07-03 16:46
I also noticed that if you name "device" the same as "name" it don't work
```
[main]
debug = 0
**devices = motorola**

[**motorola**]
**name = motorola**
type = phone
allowed = 1
```

**Comment by bboozzoo** [comment] 2016-07-03 18:29
Yes, you need to open the ports manually. There's a bunch of different firewall solutions people use, best leave this setup to the user. Perhaps the README should mention which ports need to be opened.

As for file sharing, unfortunately it's not implemented. Notifications & telephony support was a priority to me. Feel free to jump in and submit a pull request. Might be a good opportunity to look at 2 way communication, right now mconnect can only receive.

I'm not sure why you had problems with device group being picked up when loading configuration. Group name (the thing between `[..]`) and value of `name` field are entirely different things. I don't see a reason why this might pose problems. If the problem persists attach `--debug` output.

**Comment by bboozzoo** [comment] 2016-07-03 18:33
It should be possible to build the code on Fedora 24 now. Closing the issue. If there are other problems, feel free to open another one.

**Closed by bboozzoo** 2016-07-03 18:33 UTC

**Comment by Paviluf** [comment] 2016-07-04 07:08
Yes, the README should mention which ports need to be opened. It will simplify things.

Oh I didn't know that file sharing wasn't implemented. It's the only feature I need so, for now, mconnect don't suit my need. Unfortunately I'm not a developer so I can't help to implement new feature but I hope that will be implemented in the future.

Thanks !

**Comment by Paviluf** [comment] 2016-07-04 07:10
By the way don't forget that the json-glib build dependency on the readme have to be replaced by json-glib-devel ;)
